### ISSUE TITLE
Do I need to do all 3 steps in Usage part?

### ISSUE THREAD

**Issue by Veniamare** [fluffysnaff/fluffytw#3]
I'm actually almost blank in programming, and wanna ask whether I need to do all  3 steps or not, for example only do '3.Bots' step.

**Comment by fluffysnaff** [comment]
The only optional part is Visuals, everything else needs to be added to work properly

**Comment by Veniamare** [comment]
Thanks! now it works but still can't hook through corner like in first video 'Hitpoint aimbot scan', is my config somewhere incorrect?
		fConfig->aimbotCfg.enabled = true;
		fConfig->aimbotCfg.fov = 30.f;
		fConfig->aimbotCfg.accuracy = 1.f;
		fConfig->aimbotCfg.silent = true;
		fConfig->aimbotCfg.edge = false;
		fConfig->aimbotCfg.hookVisible = false;

**Comment by fluffysnaff** [comment]
Yes, `fConfig->aimbotCfg.edge = false;` means edge(or hitpoint) aimbot is disabled. Also you can increase `fConfig->aimbotCfg.accuracy` to have more points the aimbot checks for

**Comment by Veniamare** [comment]
It works perfectly! Mucho thanks for your patience ♥

**Comment by Kaitokur** [comment]
May I ask which file fConfig->aimbotCfg.edge = false is in?
