### ISSUE TITLE
the aimbot couldt work

### ISSUE THREAD

**Issue by gaogaowenwen** [fluffysnaff/fluffytw#4]
I compiled it correctly, but aimbot doesn't work

**Comment by fluffysnaff** [comment]
did you configure it?
for example `fConfig->aimbotCfg.enabled = true;`

**Comment by gaogaowenwen** [comment]
> did you configure it? for example `fConfig->aimbotCfg.enabled = true;`
I fix it .thanks a lot
I want to know what scanType can do

**Comment by gaogaowenwen** [comment]
aimbotCfg.scanType

**Comment by fluffysnaff** [comment]
Rn nothing, there used to be a bruteforce scan that would scan 2pi from tee and check intersection. It was not good enough so I removed it

**Comment by Kaitokur** [comment]
After building, is there a way to modify this toggle configuration?
