### ISSUE TITLE
can't find collision.h

### ISSUE THREAD

**Issue by Kaitokur** [fluffysnaff/fluffytw#7]
Hello pro, I'm a newbie with zero programming background. According to your readme file, I have completed most of the operations. However, I cannot find the second item "collision.h" in the file. Can you tell me where it is located? Also, would it be possible for you to provide the compiled file if possible? Thanks!

**Comment by fluffysnaff** [comment]
Hey, the path is src/game/collision.h

**Comment by Kaitokur** [comment]
5
