### ISSUE TITLE
Is it possible to control those variables after compilation or in-game?

### ISSUE THREAD

**Issue by Kaitokur** [fluffysnaff/fluffytw#8]

**Comment by fluffysnaff** [comment]
yes, when you set it up you add g_Config vars into the config. You can control g_Config variables in game

**Comment by Kaitokur** [comment]
My settings are:
fConfig->aimbotCfg.enabled = true;
fConfig->aimbotCfg.fov = 10.f;
fConfig->aimbotCfg.accuracy = 1.f;
fConfig->aimbotCfg.silent = true;
fConfig->aimbotCfg.edge = true;
fConfig->aimbotCfg.hookVisible = false;

In the game, all the settings are working except for the fov parameter. I have also tried changing the order, but it didn't make a difference. Could it be that the code is locking the fov setting?"

**Comment by Kaitokur** [comment]
In the game, the fov parameter seems to consistently stay around 30 degrees during testing.
