### ISSUE TITLE
I set fConfig->aimbotCfg.fov to 10.f, but it doesn't seem to take effect and appears to be stuck around 30. What could be the reason for this?

### ISSUE THREAD

**Issue by Kaitokur** [fluffysnaff/fluffytw#9]

**Comment by fluffysnaff** [comment]
Idk it should work. Maybe it only seems like 30

**Comment by Kaitokur** [comment]
My settings are:
fConfig->aimbotCfg.enabled = true;
fConfig->aimbotCfg.fov = 10.f;
fConfig->aimbotCfg.accuracy = 1.f;
fConfig->aimbotCfg.silent = true;
fConfig->aimbotCfg.edge = true;
fConfig->aimbotCfg.hookVisible = false;

In the game, all the settings are working except for the fov parameter. I have also tried changing the order, but it didn't make a difference. Could it be that the code is locking the fov setting?"

**Comment by Kaitokur** [comment]
In the game, the fov parameter seems to consistently stay around 30 degrees during testing.

**Comment by fluffysnaff** [comment]
there shouldn't be any lock
